// import { Geist, Geist_Mono } from "next/font/google";
import { Poppins } from "next/font/google";
import "./globals.css";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["600", "700"], 
  variable: "--font-poppins",
});

export const metadata = {
  title: "Ecommerce-Website",
  description: "Generated by Mazen",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable}` }
      >
  
        {children}
      
      </body>
    </html>
  );
}
